carla_params:
  epoch_name: auditory_onset
  time_window:
  - 0.01
  - 1.0
  electrodes: 13-16,24
  n_bootstrap: 100
  virtual_reference: yes
  sensitive: yes
  min_size: 2
  absolute_rank: yes
changes:
- group_name: G
  electrodes: 13-16,24
  reference_type: Common Average Reference
  reference_signal: ref_13-16
electrode_group:
  '1':
    name: G
    electrodes: 13-16,24
project_name: demo
reference_name: _unsaved
subject_code: DemoSubject
