annot_types: ~
controllers: []
coordinate_sys: ''
data_source: Uploads
data_source_pipeline: power_explorer/power_explorer-22_09_03-22_54_46
data_source_pipeline_target: omnibus_results
data_source_project: demo
main_camera: []
overlay_types: ~
override_radius: .na
project_name: YAEL
shiny_outputId: custom_3d_viewer-viewer_ready
streamline_types:
- default/*
- alic/*
subject_code: CIT168
surface_types: ~
uploaded_source: YAEL-electrodes.fst
use_spheres: no
use_template: no
