---
title: "Normalization Quality Report"
description: | 
  <small><i>
    An automated report generated by 
    <a target="_blank" href="https://doi.org/10.1523/ENEURO.0328-23.2023">YAEL</a>
    via 
    <a target="_blank" href="https://rave.wiki">RAVE</a> 
    on `r strftime(Sys.Date(), '%b %d, %Y')`
  </i></small>
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    theme: flatly
    code_folding: true
    self_contained: true
    toc: true
    toc_depth: 3
    toc_float: true
    css: "report_styles.css"
  html_document:
    theme: flatly
    code_folding: hide
    self_contained: true
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  eval = TRUE,
  echo = TRUE,
  collapse = TRUE,
  warning = FALSE,
  message = FALSE
)

# For debug, set current environment
# setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

*Click on the `Show` button to reveal preparation scripts.*

```{r initial_setup}
#| results: 'hide'

# This code block sets up the engine environment
# Please do not remove me
pipeline <- ravepipeline::pipeline_from_path(".")
subject_code <- pipeline$get_settings("subject_code")
project_name <- pipeline$get_settings("project_name")
subject <- ravecore::RAVESubject$new(project_name = project_name,
                                     subject_code = subject_code,
                                     strict = FALSE)
imaging_path <- subject$imaging_path

normalization_path <- file.path(imaging_path, "normalization")



if(!dir.exists(normalization_path)) {
  stop(
    "Unable to find normalization path. ",
    "The MR normalization report is only available after you run ",
    "'YAEL-only' or 'YAEL+recon-all' in the preprocessing")
}

available_templates <- unique(c("mni_icbm152_nlin_asym_09b", 
                                rpyANTs:::BUILTIN_TEMPLATES))
yael_process <- ravecore::as_yael_process(subject)

has_mapping <- vapply(available_templates, function(name) {
  mapping <- yael_process$get_template_mapping(template_name = name)
  return(!is.null(mapping))
}, FUN.VALUE = FALSE)
available_mapping <- available_templates[has_mapping]

if(!length(available_mapping)) {
  stop(
    "Unable to find valid normalization files. ",
    "The MR normalization report is only available after you run ",
    "'YAEL-only' or 'YAEL+recon-all' in the preprocessing")
}

diagnose_normalization <- function(template_name) {
  # template_name <- available_mapping[[1]]
  
  # get template image
  info <- yael_process$get_template_mapping(template_name, 
                                            relative = TRUE)
  template <- rpyANTs::ensure_template(template_name)
  template_path <- file.path(template, "T1.nii.gz")
  template_image <- ieegio::read_volume(template_path)
  
  # Map t1 to template
  t1w_path <- yael_process$get_input_image("T1w")
  t1_in_template <- yael_process$transform_image_to_template(
    t1w_path, template_name = template_name, verbose = FALSE)
  t1_in_template2 <- ieegio::as_ieegio_volume(t1_in_template)
  
  svg_axial <- ravecore::plot_volume_slices(
    template_image, overlay = t1_in_template2, which = "axial", 
    nc = 6, depths = seq(-70, 85, length.out = 24)
  )
  
  svg_sagittal <- ravecore::plot_volume_slices(
    template_image, overlay = t1_in_template2, which = "sagittal", 
    nc = 6, depths = seq(-70, 70, length.out = 24)
  )
  
  svg_coronal <- ravecore::plot_volume_slices(
    template_image, overlay = t1_in_template2, which = "coronal", 
    nc = 6, depths = seq(-100, 70, length.out = 24)
  )
  
  list(
    axial = svg_axial,
    sagittal = svg_sagittal,
    coronal = svg_coronal
  )
}
diagnose_results <- structure(
  lapply(available_mapping, diagnose_normalization),
  names = available_mapping
)
```

## Subject ID: ``r subject$subject_id``

```{r, results='asis', layout="l-screen-inset"}
htmltools::tagList(lapply(available_mapping, function(mapping_template) {
  htmltools::tagList(
    htmltools::h3("Template: ", mapping_template),
    htmltools::div(
      style = "width: 100%",
      diagnose_results[[mapping_template]]
    )
  )
})) 
```










## Citations

The module depends on the following work. Please cite our YAEL paper for electrode localization pipelines and RAVE paper for 3D visualization.

```{r, results='asis', echo = FALSE}
print(pipeline$description$Citations, style = "html")
```
