analysis_electrodes: '15'
analysis_ranges: ~
condition_groups:
  '1':
    label: AV
    conditions:
    - last_av
    - drive_av
    - known_av
    - meant_av
  '2':
    label: A
    conditions:
    - last_a
    - drive_a
    - known_a
    - meant_a
  '3':
    label: V
    conditions:
    - last_v
    - drive_v
    - known_v
    - meant_v
epoch_choice: auditory_onset
epoch_choice__trial_ends: 2
epoch_choice__trial_ends_rel_to_event: ~
epoch_choice__trial_starts: -1
epoch_choice__trial_starts_rel_to_event: ~
filter_configurations:
- type: decimate
  by: 2.0
  auto: yes
- type: firls
  high_pass_freq: 1
  low_pass_freq: 30
- type: decimate
  by: 1
  auto: no
- type: baseline
  windows:
  - -0.67
  - -0.51
loaded_electrodes: 13-16,24
project_name: demo
reference_name: default
subject_code: DemoSubject
