analysis_electrodes: '14'
analysis_event: Trial Onset
analysis_ranges: ~
condition_groups:
  '1':
    label: AV
    conditions:
    - last_av
    - drive_av
    - known_av
    - meant_av
  '2':
    label: A
    conditions:
    - last_a
    - drive_a
    - known_a
    - meant_a
  '3':
    label: V
    conditions:
    - last_v
    - drive_v
    - known_v
    - meant_v
crp_detection_window:
- 0.01
- 2.0
crp_onset_border: earliest_possible
crp_threshold_quantile: 98.0
crp_time_step: 5
epoch_choice: auditory_onset
epoch_choice__trial_ends: 2
epoch_choice__trial_ends_rel_to_event: ~
epoch_choice__trial_starts: -1
epoch_choice__trial_starts_rel_to_event: ~
filter_configurations:
- type: detrend
- type: demean
- type: decimate
  by: 2.0
  auto: yes
- type: firls
  high_pass_freq: 1
  low_pass_freq: 30
- type: decimate
  by: 5.0
  auto: yes
- type: baseline
  windows:
  - -1
  - 0
loaded_electrodes: 13-16,24
project_name: demo
reference_name: default
subject_code: DemoSubject
