---
title: "Notch-Filter Diagnostic Plots"
output: html_document
date: "`r Sys.Date()`"
params:
  electrodes: ~
---

```{r setup, echo = FALSE, results='hide', eval=TRUE}
# This code block sets up the engine environment
# Please do not remove me
pipeline <- ravepipeline::pipeline_from_path(".")
shared_env <- pipeline$shared_env()

project_name <- pipeline$get_settings(key = "project_name")
subject_code <- pipeline$get_settings(key = "subject_code")
diagnostic_plot_params <- pipeline$get_settings(key = "diagnostic_plot_params")
diagnose_notch_filters <- shared_env$diagnose_notch_filters

subject <- raveio::RAVESubject$new(
  project_name = project_name, 
  subject_code = subject_code, 
  strict = FALSE
)
diagnostic_plot_params <- as.list(diagnostic_plot_params)
background <- diagnostic_plot_params$background
foreground <- diagnostic_plot_params$foreground

if(!length(background) == 1) {
  background <- "white"
}
if(!length(foreground) == 1) {
  foreground <- "black"
}
winlen <- as.numeric(diagnostic_plot_params$window_length)
if(!length(winlen) || is.na(winlen)) {
  winlen <- "auto"
}
  
max_freq <- as.numeric(diagnostic_plot_params$max_frequency)
if(!length(max_freq) || is.na(max_freq)) {
  max_freq <- 300
}
nbins <- as.numeric(diagnostic_plot_params$histogram_bins)
if(!length(nbins) || is.na(nbins)) {
  nbins <- 50
}

```

## Subject ID: `r subject$subject_id`



Welch-periodogram parameters:

* Window size (seconds): `r winlen` seconds
* Maximum frequency (Hz) to plot: `r max_freq` Hz

```{r generate_diagnostic_plots, fig.height=7, fig.width=12, out.width="100%", echo = FALSE}
filtered_channels <- subject$electrodes[subject$notch_filtered]
if(length(params$electrodes)) {
  filtered_channels <- filtered_channels[filtered_channels %in% params$electrodes]
}
diagnose_notch_filters(
  subject = subject,
  electrodes = filtered_channels,
  max_freq = max_freq,
  winlen = winlen,
  nbins = nbins,
  bg = background,
  fg = foreground,
  cex = font_size,
  std = 3,
  lwd = 0.3,
  quiet = TRUE
)
```
