# agents/tools/shiny_input_update.R
#
# Shiny input interaction tools (shiny_input_info, shiny_input_update,
# shiny_output_info, shiny_query_ui) are auto-generated by shidashi's
# load_module_resource() via mcp_wrapper_input_output().
#
# No manual definition is needed here.  This file is kept as a
# documentation stub.  Enable/disable individual tools per module in
# each module's agents.yaml.
